<html>
<head>
</head>
<body>
<table style="width: 100%">
    <tr>
        <td colspan="2" style="text-align: center">
            <h1><strong>Наряд заказ</strong></h1>
        </td>
    </tr>
    <tr>
        <td>
            <strong>Номер запроса</strong>
        </td>
        <td>
        ${id}
        </td>
    </tr>
    <tr>
        <td>
            <strong>Тема запроса</strong>
        </td>
        <td>
        ${theme}
        </td>
    </tr>
    <tr>
        <td>
            <strong>Описание запроса</strong>
        </td>
        <td>
        ${description}
        </td>
    </tr>
    <tr>
        <td>
            <strong>Статус запроса</strong>
        </td>
        <td>
        ${status}
        </td>
    </tr>
    <tr>
        <td>
            <strong>Исполнитель</strong>
        </td>
        <td>
        ${worker}
        </td>
    </tr>
    <tr>
        <td>
            <strong>Заявитель</strong>
        </td>
        <td>
        ${applicant}
        </td>
    </tr>
    <tr>
        <td>
            <strong>Адрес заявителя</strong>
        </td>
        <td>
        ${adres}
        </td>
    </tr>
</table>
</body>
</html>
